# Project: TrabalhoLista
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Principal.o Lista.o Title.o
LINKOBJ  = Principal.o Lista.o Title.o
LIBS     = -L"C:/Users/Public/Desktop/WorkStation - Thyago/Dev-Cpp/MinGW64/lib" -L"C:/Users/Public/Desktop/WorkStation - Thyago/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/Public/Desktop/WorkStation - Thyago/Dev-Cpp/MinGW64/include" -I"C:/Users/Public/Desktop/WorkStation - Thyago/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Public/Desktop/WorkStation - Thyago/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Public/Desktop/WorkStation - Thyago/Dev-Cpp/MinGW64/include" -I"C:/Users/Public/Desktop/WorkStation - Thyago/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Public/Desktop/WorkStation - Thyago/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Public/Desktop/WorkStation - Thyago/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = TrabalhoLista.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Principal.o: Principal.c
	$(CC) -c Principal.c -o Principal.o $(CFLAGS)

Lista.o: Lista.c
	$(CC) -c Lista.c -o Lista.o $(CFLAGS)

Title.o: Title.c
	$(CC) -c Title.c -o Title.o $(CFLAGS)
